### ISSUE TITLE
Can't start

### ISSUE THREAD

**Issue by zhongjixiuxing** [TwanoO67/ng2-admin-lte#11]
Hi Guys:
    I run "npm install", and then execute "npm start", it can't start up this project. 
    I run it in win7 X86_64,  node: V6.0.0, npm: V3.8.0
    The follow is my exception information, please help me.
![image](https://cloud.githubusercontent.com/assets/8935235/14937039/ce86fdec-0f2d-11e6-95fe-40d26b97f5b3.png)

[npm-debug.log.txt](https://github.com/TwanoO67/ng2-admin-lte/files/243698/npm-debug.log.txt)

Best Regards
AX

**Comment by TwanoO67** [comment]
It seems that you're missing "concurently", maybe you should install the dev dépendencies, using "npm install --dev"

**Comment by zhongjixiuxing** [comment]
Yes... now, i meeting other trouble:

![p15 8zll381_8u2m 58oph](https://cloud.githubusercontent.com/assets/8935235/14939995/3b69f3b4-0f93-11e6-9639-98376462b0e7.png)

![image](https://cloud.githubusercontent.com/assets/8935235/14939929/405da1fc-0f90-11e6-84fb-50c140ce465a.png)

**Comment by TwanoO67** [comment]
Syntax of ngFor changes in the angular2 beta17 causing breaking change.
I will upgrade as soon as possible, but in the mean time, you can force install the angular2 beta16:
in package.json, replace 
_"angular2": "^2.0.0-beta.13",_
by
_"angular2": "2.0.0-beta.16",_

and reload your "npm install"

**Comment by TrinhNgocThanh** [comment]
I changed "angular2": "2.0.0-beta.16", & and reload your "npm install" but the same problem..

**Comment by TwanoO67** [comment]
I'm currently upgrading to angular-rc1 (in the branch named aswell) so this won't be a problem anymore.
You can try the new branch, "npm install" and report here if you have issues

**Comment by TwanoO67** [comment]
I just pushed a new released on master, this one works with the angular2 rc2 and router v3
but not all widgets / services has been ported yet.
But this issue can be closed
