### ISSUE TITLE
Right control bar does not toggle

### ISSUE THREAD

**Issue by hakonamatata** [TwanoO67/ng2-admin-lte#17]
Hi

It seems like the right control bar does not work. At least not for me. 
When I click on the "control-sidebar" the page just redirect to the home page

```
        <!-- Control Sidebar Toggle Button -->
        <li>
          <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
        </li>
```

From what I understand the toggle function is here: 
```
  $.AdminLTE.controlSidebar = {
    //instantiate the object
    activate: function () {

      console.log("activate control-sidebar");

      //Get the object
      var _this = this;
      //Update options
      var o = $.AdminLTE.options.controlSidebarOptions;
      //Get the sidebar
      var sidebar = $(o.selector);
      //The toggle button
      var btn = $(o.toggleBtnSelector);

      //Listen to the click event
      btn.on('click', function (e) {
        e.preventDefault();

        console.log("toggle right sidebar");

        //If the sidebar is not open
        if (!sidebar.hasClass('control-sidebar-open')
            && !$('body').hasClass('control-sidebar-open')) {
          //Open the sidebar
          _this.open(sidebar, o.slide);
        } else {
          _this.close(sidebar, o.slide);
        }
      });
```

Seems like jquery can't find the toggle button and the e.PreventDefault() etc is not triggered

**Comment by TwanoO67** [comment]
Bug confirmed: the "o.toggleBtnSelector" seems to be related to the data-toggle attribute, which is overridden by ng2...
I'm looking for a solution without modifying adminLTE...

**Comment by atticae** [comment]
I solved this exact problems a few months ago, might be of help:

You have to call `$.AdminLTE.controlSidebar.activate()` in ngAfterViewInit of your ControlSidebarComponent.

This is how my component looks:

```
import { Component, OnInit, AfterViewInit } from '@angular/core';

declare var jQuery: any;

@Component({
  moduleId: module.id,
  selector: 'control-sidebar',
  templateUrl: 'control-sidebar.component.html'
})
export class ControlSidebarComponent implements OnInit, AfterViewInit {

  constructor() { }

  ngOnInit() {

  }

  ngAfterViewInit() {
    if (jQuery.AdminLTE && jQuery.AdminLTE.controlSidebar) {
      jQuery.AdminLTE.controlSidebar.activate();
    }
  }
}
```

**Comment by TwanoO67** [comment]
Nice! :)
Don't hesitate to make a pull request, if you want your name to be quoted on the project ;)

**Comment by TwanoO67** [comment]
This is also solved by the new compilation process

**Comment by llotall** [comment]
@magnattic Hello , please can you describe more detail your solution of this bug?  I'm a begginer in SPA's on angular.
What is contains templateUrl: 'control-sidebar.component.html' ?

**Comment by llotall** [comment]
@TwanoO67 Hello, please can you say me about what you meaning about compilation process?

**Comment by TwanoO67** [comment]
This is a very old bug and the correction is already merged in the repo.
It add noting to do with the templateUrl.
What is your problem @llotall ?

**Comment by llotall** [comment]
@TwanoO67 same problem in project i try invoke sidebar by
 <li>
          <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
</li>
but nothing to do

**Comment by llotall** [comment]
@TwanoO67 Do you know how to add custom scrollbar in sidebar component?
