### ISSUE TITLE
Build production mode 

### ISSUE THREAD

**Issue by mkermouss** [TwanoO67/ng2-admin-lte#22]
i have an issue in building the project in production mode, it gives some errors : 
- some files are missing (404 not found) like (jquery - bootstrap.min.js - app.min.js - app.routes.js)
- the _service folder and files within are missing too

**Comment by TwanoO67** [comment]
Sorry for the late answer...
I've just tested with "ng build" all is working correctly (and is available in the "dist" folder)
but with "ng build --prod" brocolli seems to crash with no explicable reason...
maybe something in the bootstraping process is failing here.

But as angular-cli is going to change from brocoli to webpack, I'm not going to maintain this version.
(There's to much breaking change from angular team that I need to rewrite anyway)
I'm waiting for RC6 to go out, and angular-cli to be updated to webpack et router capacity before updating this package.

Sorry for the inconvenience but for the moment you should stay on the "ng build" version.

**Comment by TwanoO67** [comment]
This should be fixed by the last commit, can you confirm?
