### ISSUE TITLE
menu-aside collapsed

### ISSUE THREAD

**Issue by cindoum** [TwanoO67/ng2-admin-lte#24]
Bonjour,

Lorsque le menu est collapse, une partie du title reste affiche et lorsquon hover l'element, il saffiche par dessus la page.

Un overflow hiden devrait regler le probleme de hover, je crois quon seul licon devrait etre afficher en mode collapse

![capture](https://cloud.githubusercontent.com/assets/2387496/19358339/8a63e538-9143-11e6-906e-30dcdb3c0ced.PNG)

**Comment by TwanoO67** [comment]
Ok c'est patché

**Comment by cindoum** [comment]
could you please link me the commit?

**Comment by TwanoO67** [comment]
https://github.com/TwanoO67/ng2-admin-lte/commit/2f33e255f5e78ae47707e4890760ebdba0493034

**Comment by cindoum** [comment]
Thanks,
au cas ou tu ne connais pas. lorsque tu commit un fix pour un issue tu peux faire ceci:

`git commit -m "close #24 fix things".` ou
` git commit -m "fix #24 fix things`

De cette facon, l'issue sera close automatiquement et le commit sera linker a lissue, donc le submitter pourra voir directement le commit number ;)

**Comment by TwanoO67** [comment]
Cool :) j'ai l'habitude de gitlab donc je me suis gouré dans la syntaxe ^^
