### ISSUE TITLE
Menu brand link - reload app

### ISSUE THREAD

**Issue by cindoum** [TwanoO67/ng2-admin-lte#25]
Bonjour,

Lorsque l'on click sur le brand dans le menu, l'application reload complement au lieu de simplement router vers #/.

Egalement, lors du reload de l'application, il serait bien d'avoir un loading screen. Pour le moment, tant quangular n'est pas bootstraper, on voit le footer et quelque autres elements dans la page.

**Comment by TwanoO67** [comment]
Pour le lien sur brand, il manque le routerlink. Mais je suis sur mobile donc je patcherais ce soir.

Pour la page de loading, l'application est ouverte au PR ;)

**Comment by cindoum** [comment]
Jessaye de pusher une branch sur ton repo pour faire un PR (pour le routerLink), mais ca ne fonctionne pas (permission denied)

**Comment by TwanoO67** [comment]
C'est normal sur github, pour faire une pull request, tu dois forker le repo, puis pusher la branche sur ton propre compte (tu peux rajouter ton depot en tant que remote sur le meme dossier si tu veux).
Une fois que le code est dans ton repo, tu peux en faire une pull request directement dans l'interface

**Comment by TwanoO67** [comment]
Le lien sur brand est corrigé
