### ISSUE TITLE
Idea - Folder structure - Should not have _ in folder name

### ISSUE THREAD

**Issue by cindoum** [TwanoO67/ng2-admin-lte#26]
I think it would be a good practice to not have _models, _services and _widget. 
Also, having a pages folder to hold 'home' and 'page-num' would be great.

by the way, your doing a good job!

**Comment by TwanoO67** [comment]
The idea of the _ was to separate the "core fonctionnality folders" from "module folders". (back to ng2 beta where it was no real module folder)
Now the convention seems to have:
shared (for widgets, directives, pipes and models) => that can be imported several time
core (for services) => that should be provided only once
other_modules_folders... (containing their own services, pipes, widgets etc.. not shared among the app)
 
And you are right in this same idea, we should have a pages folder too.
