### ISSUE TITLE
Authentication - auth0

### ISSUE THREAD

**Issue by cindoum** [TwanoO67/ng2-admin-lte#29]
Hi,

i'm about to add auth0-lock for authentication. With aut0 and auth0-lock, you can have a full authentication process (login/logout/sigin/reset pwd/google auth etc...).

Is that somewthing you would like a PR for?

https://auth0.com/

**Comment by TwanoO67** [comment]
It's seems very cool =)
I'll gladly take a PR for that.

**Comment by cindoum** [comment]
Ok, on it ;)

**Comment by solovieff** [comment]
+ for this!

**Comment by TwanoO67** [comment]
closed by @cindoum PR
