### ISSUE TITLE
Intégrer un service pour firebase

### ISSUE THREAD

**Issue by TwanoO67** [TwanoO67/ng2-admin-lte#3]

**Comment by cindoum** [comment]
I think i could help you with this one as i plan to do it on my side. Add firebase for data layer and auth0-lock for authentication. Let me know if you want us to collaborate on this one.

**Comment by TwanoO67** [comment]
I was thinking of that at the beginning of the year, but I had no time to discover firebase yet, that's why I closed that issue.
But If you're planning to integrate to your projet, I would be glad to had it inhere :)

**Comment by cindoum** [comment]
I will integrate Angularfire2 (wrapper around firebase for ng2) and probably firebase too (as angularFire still miss some key features for authentication). 

Once its done and working on my side, ill create a PR.

**Comment by cindoum** [comment]
Je suis en train de terminer une page qui utilise Firebase (add / delete / update) d'une liste d'object sur firebase. Jai cherche un module de notification dans ton starter kit mais je n'ai rien trouve (to show, Object x has been deleted / updated). 
Est ce correct si jimporte un module de Toastr (https://github.com/Stabzs/Angular2-Toaster) ?

**Comment by TwanoO67** [comment]
D'habitude j'utilise bootbox, mais c'est un wrapper autour de jquery ( ce que j'essaye de limiter).
Donc si le tiens est bien du pur angular2 c'est mieux, go ! :)

**Comment by TwanoO67** [comment]
Je viens de vérifier le package.json du Toaster, il est clean tu peux y aller :)
