### ISSUE TITLE
Can't start ng2-admin-lte template

### ISSUE THREAD

**Issue by makafsal** [TwanoO67/ng2-admin-lte#31]
After using '**npm install**', when trying to start template using '**npm start**', it not works. It throws an error

**npm install shows this error**:
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN angularfire2@2.0.0-beta.5 requires a peer of @types/request@0.0.30 but none was installed.

**npm start show following error**:
_Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
ENOENT: no such file or directory, stat '/home/afsal/Downloads/ng2-admin/ng2-lte/ng2-admin-lte/src/assets'
Error: ENOENT: no such file or directory, stat '/home/afsal/Downloads/ng2-admin/ng2-lte/ng2-admin-lte/src/assets'_

why this happens..?
please help me...

**Comment by TwanoO67** [comment]
It seems that you are missing some files.
This error happen when moving folders during compilation process

**Comment by makafsal** [comment]
It is freshly downloaded one from github.

**Comment by TwanoO67** [comment]
Then I dont know... It works for me and every one else. 
Give us more info about your env
