### ISSUE TITLE
Bundling assets/all-in index.html

### ISSUE THREAD

**Issue by ggrnd0** [TwanoO67/ng2-admin-lte#32]
How to make bundles with minified assets?

Do you have alternate `index.html` without including cdn sources?

**Comment by ggrnd0** [comment]
Is it possible make all plugins as node dependencies?

**Comment by cindoum** [comment]
+1 for removing the public/plugins

**Comment by TwanoO67** [comment]
Will try that, but the only one that I really don't know how to include, is font-awesome.
All the times I tried to package that one the inner css dependencies loading where crashing.

**Comment by TwanoO67** [comment]
Ok, I removed js and css from plugins and replaced them with node_modules less inclusions and scripts in angular-cli.json

But the fonts from font-awesome are still needed

**Comment by ggrnd0** [comment]
something like

	{
	  "apps": [
		{
		  "root": "sources/main",
		  "outDir": "processed/main.bundled",
		  "assets": [ "assets" ],
		  "index": "index.html",
		  "main": "main.ts",
		  "test": "test.ts",
		  "tsconfig": "tsconfig.json",
		  "prefix": "app",
		  "mobile": false,
		  "styles": [
			"../../node_modules/bootstrap/dist/css/bootstrap.css",
			"../../node_modules/font-awesome/css/font-awesome.css",
			"../../node_modules/admin-lte/dist/css/AdminLTE.css",
			"../../node_modules/admin-lte/dist/css/skins/skin-blue.css",
			"../../node_modules/toastr/build/toastr.css",
			"styles.css"
		  ],
		  "scripts": [
			"../../node_modules/lodash/lodash.js",
			"../../node_modules/jquery/dist/jquery.js",
			"../../node_modules/bootstrap/dist/js/bootstrap.js",
			"../../node_modules/toastr/build/toastr.min.js",
			"../../node_modules/admin-lte/dist/js/app.js"
		  ],
		  "environments": {
			"source": "environments/environment.ts",
			"dev": "environments/environment.ts",
			"prod": "environments/environment.prod.ts"
		  }
		}
	  ],
	}

**Comment by TwanoO67** [comment]
That won't work because of the css inclusion in font-awesome

**Comment by ggrnd0** [comment]
@TwanoO67 , there is example. All works fine i think..
https://github.com/ggrnd0/admin-lte-ng-example

**Comment by TwanoO67** [comment]
I dont understand the différence with the angular-cli.json on Master.
What do you need more ?

**Comment by ggrnd0** [comment]
@TwanoO67 
> That won't work because of the css inclusion in font-awesome

it is works.

**Comment by TwanoO67** [comment]
I really dont understand... 
There's no more cdn inclusion in this repo since a month. 
If I'm missing something please submit a PR
