### ISSUE TITLE
npm install fails on dependencies

### ISSUE THREAD

**Issue by mbateman66** [TwanoO67/ng2-admin-lte#37]
With a fresh clone from master, npm install fails with:
```
npm WARN angular2-jwt@0.1.25 requires a peer of rxjs@5.0.0-beta.12 but none was installed.
npm WARN angularfire2@2.0.0-beta.6 requires a peer of rxjs@5.0.0-beta.12 but none was installed.
npm WARN angular2-toaster@1.0.2 requires a peer of rxjs@5.0.0-beta.12 but none was installed.
npm WARN @angular/http@2.2.0 requires a peer of rxjs@5.0.0-beta.12 but none was installed.
npm WARN @angular/router@3.0.0 requires a peer of rxjs@5.0.0-beta.12 but none was installed.
npm WARN @angular/core@2.2.0 requires a peer of rxjs@5.0.0-beta.12 but none was installed.
```

**Comment by TwanoO67** [comment]
Those are only warning because the rxjs included is more recent

**Comment by mbateman66** [comment]
Ah, OK. I thought maybe that was the cause of all the errors that show up on npm start...

`[default] /home/mbateman/src/iot/ng2-admin-lte/node_modules/angularfire2/node_modules/firebase/firebase.d.ts:12:9
    Duplicate identifier 'Promise'.
[default] /home/mbateman/src/iot/ng2-admin-lte/node_modules/angularfire2/node_modules/firebase/firebase.d.ts:17:9
    Duplicate identifier 'Promise_Instance'.
[default] /home/mbateman/src/iot/ng2-admin-lte/node_modules/angularfire2/node_modules/firebase/firebase.d.ts:130:9
    Duplicate identifier 'EmailAuthProvider'.
[default] /home/mbateman/src/iot/ng2-admin-lte/node_modules/angularfire2/node_modules/firebase/firebase.d.ts:135:9
    Duplicate identifier 'EmailAuthProvider_Instance'.
[default] /home/mbateman/src/iot/ng2-admin-lte/node_modules/angularfire2/node_modules/firebase/firebase.d.ts:144:9
    Duplicate identifier 'FacebookAuthProvider'.
[default] /home/mbateman/src/iot/ng2-admin-lte/node_modules/angularfire2/node_modules/firebase/firebase.d.ts:148:9
    Duplicate identifier 'FacebookAuthProvider_Instance'.
[default] /home/mbateman/src/iot/ng2-admin-lte/node_modules/angularfire2/node_modules/firebase/firebase.d.ts:153:9
    Duplicate identifier 'GithubAuthProvider'.
[default] /home/mbateman/src/iot/ng2-admin-lte/node_modules/angularfire2/node_modules/firebase/firebase.d.ts:157:9
    Duplicate identifier 'GithubAuthProvider_Instance'.
[default] /home/mbateman/src/iot/ng2-admin-lte/node_modules/angularfire2/node_modules/firebase/firebase.d.ts:162:9
    Duplicate identifier 'GoogleAuthProvider'.
[default] /home/mbateman/src/iot/ng2-admin-lte/node_modules/angularfire2/node_modules/firebase/firebase.d.ts:167:9
    Duplicate identifier 'GoogleAuthProvider_Instance'.
[default] /home/mbateman/src/iot/ng2-admin-lte/node_modules/angularfire2/node_modules/firebase/firebase.d.ts:172:9
    Duplicate identifier 'TwitterAuthProvider'.
[default] /home/mbateman/src/iot/ng2-admin-lte/node_modules/angularfire2/node_modules/firebase/firebase.d.ts:177:9
    Duplicate identifier 'TwitterAuthProvider_Instance'.
[default] /home/mbateman/src/iot/ng2-admin-lte/node_modules/angularfire2/node_modules/firebase/firebase.d.ts:181:8
    Duplicate identifier 'UserCredential'.
[default] /home/mbateman/src/iot/ng2-admin-lte/node_modules/angularfire2/node_modules/firebase/firebase.d.ts:339:8
    Duplicate identifier 'StringFormat'.
[default] /home/mbateman/src/iot/ng2-admin-lte/node_modules/angularfire2/node_modules/firebase/firebase.d.ts:340:7
    Duplicate identifier 'StringFormat'.
[default] /home/mbateman/src/iot/ng2-admin-lte/node_modules/angularfire2/node_modules/firebase/firebase.d.ts:347:8
    Duplicate identifier 'TaskEvent'.
[default] /home/mbateman/src/iot/ng2-admin-lte/node_modules/angularfire2/node_modules/firebase/firebase.d.ts:348:7
    Duplicate identifier 'TaskEvent'.
[default] /home/mbateman/src/iot/ng2-admin-lte/node_modules/angularfire2/node_modules/firebase/firebase.d.ts:352:8
    Duplicate identifier 'TaskState'.
[default] /home/mbateman/src/iot/ng2-admin-lte/node_modules/angularfire2/node_modules/firebase/firebase.d.ts:353:7
    Duplicate identifier 'TaskState'.
[default] /home/mbateman/src/iot/ng2-admin-lte/node_modules/angularfire2/node_modules/firebase/firebase.d.ts:390:3
    Duplicate identifier 'export='.
[default] /home/mbateman/src/iot/ng2-admin-lte/node_modules/firebase/firebase.d.ts:12:9
    Duplicate identifier 'Promise'.
[default] /home/mbateman/src/iot/ng2-admin-lte/node_modules/firebase/firebase.d.ts:17:9
    Duplicate identifier 'Promise_Instance'.
[default] /home/mbateman/src/iot/ng2-admin-lte/node_modules/firebase/firebase.d.ts:132:9
    Duplicate identifier 'EmailAuthProvider'.
[default] /home/mbateman/src/iot/ng2-admin-lte/node_modules/firebase/firebase.d.ts:137:9
    Duplicate identifier 'EmailAuthProvider_Instance'.
[default] /home/mbateman/src/iot/ng2-admin-lte/node_modules/firebase/firebase.d.ts:146:9
    Duplicate identifier 'FacebookAuthProvider'.
[default] /home/mbateman/src/iot/ng2-admin-lte/node_modules/firebase/firebase.d.ts:150:9
    Duplicate identifier 'FacebookAuthProvider_Instance'.
[default] /home/mbateman/src/iot/ng2-admin-lte/node_modules/firebase/firebase.d.ts:156:9
    Duplicate identifier 'GithubAuthProvider'.
[default] /home/mbateman/src/iot/ng2-admin-lte/node_modules/firebase/firebase.d.ts:160:9
    Duplicate identifier 'GithubAuthProvider_Instance'.
[default] /home/mbateman/src/iot/ng2-admin-lte/node_modules/firebase/firebase.d.ts:166:9
    Duplicate identifier 'GoogleAuthProvider'.
[default] /home/mbateman/src/iot/ng2-admin-lte/node_modules/firebase/firebase.d.ts:171:9
    Duplicate identifier 'GoogleAuthProvider_Instance'.
[default] /home/mbateman/src/iot/ng2-admin-lte/node_modules/firebase/firebase.d.ts:177:9
    Duplicate identifier 'TwitterAuthProvider'.
[default] /home/mbateman/src/iot/ng2-admin-lte/node_modules/firebase/firebase.d.ts:182:9
    Duplicate identifier 'TwitterAuthProvider_Instance'.
[default] /home/mbateman/src/iot/ng2-admin-lte/node_modules/firebase/firebase.d.ts:187:8
    Duplicate identifier 'UserCredential'.
[default] /home/mbateman/src/iot/ng2-admin-lte/node_modules/firebase/firebase.d.ts:358:8
    Duplicate identifier 'StringFormat'.
[default] /home/mbateman/src/iot/ng2-admin-lte/node_modules/firebase/firebase.d.ts:359:7
    Duplicate identifier 'StringFormat'.
[default] /home/mbateman/src/iot/ng2-admin-lte/node_modules/firebase/firebase.d.ts:366:8
    Duplicate identifier 'TaskEvent'.
[default] /home/mbateman/src/iot/ng2-admin-lte/node_modules/firebase/firebase.d.ts:367:7
    Duplicate identifier 'TaskEvent'.
[default] /home/mbateman/src/iot/ng2-admin-lte/node_modules/firebase/firebase.d.ts:371:8
    Duplicate identifier 'TaskState'.
[default] /home/mbateman/src/iot/ng2-admin-lte/node_modules/firebase/firebase.d.ts:372:7
    Duplicate identifier 'TaskState'.
[default] /home/mbateman/src/iot/ng2-admin-lte/node_modules/firebase/firebase.d.ts:409:3
    Duplicate identifier 'export='.
[default] /home/mbateman/src/iot/ng2-admin-lte/node_modules/rxjs/observable/PairsObservable.d.ts:1:1
    Cannot find type definition file for 'chai'.
[default] /home/mbateman/src/iot/ng2-admin-lte/node_modules/rxjs/observable/dom/AjaxObservable.d.ts:1:1
    Cannot find type definition file for 'chai'.
[default] Checking finished with 42 errors`

**Comment by TwanoO67** [comment]
Try removing firebase from your package.json it seems to be already included by angularfire2.
Then delete node_modules and try re-installing

**Comment by mbateman66** [comment]
Cool. Getting closer...

`[default] /home/mbateman/src/iot/ng2-admin-lte/node_modules/rxjs/observable/PairsObservable.d.ts:1:1
    Cannot find type definition file for 'chai'.
[default] /home/mbateman/src/iot/ng2-admin-lte/node_modules/rxjs/observable/dom/AjaxObservable.d.ts:1:1
    Cannot find type definition file for 'chai'.`

**Comment by TwanoO67** [comment]
Hmmm...

Try: ng install --save @types/rxjs

**Comment by mbateman66** [comment]
ng install does not seem to be a valid command. I assume you meant npm install. But that does not work either...

`mbateman@mdbdev1:~/src/iot/iot-ui$ npm install --save @types/rxjs
npm ERR! Linux 4.4.0-45-generic
npm ERR! argv "/home/mbateman/.nvm/versions/node/v6.9.1/bin/node" "/home/mbateman/.nvm/versions/node/v6.9.1/bin/npm" "install" "--save" "@types/rxjs"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/@types%2frxjs
npm ERR! 404
npm ERR! 404  '@types/rxjs' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/mbateman/src/iot/iot-ui/npm-debug.log`

**Comment by mbateman66** [comment]
This worked...

npm install --save @types/chai

**Comment by TwanoO67** [comment]
Yeah that's what I ment.. But it doesnt seems good. 

So maybe: npm install --save @types/chai

**Comment by mbateman66** [comment]
Thanks for sticking with me on this. Looks like a lot of dependency changes recently. :-(

**Comment by TwanoO67** [comment]
No problem :)

If all is working, don't forget to do a PR with your changes ;)

**Comment by mbateman66** [comment]
I am brand new to git and GitHub, so I'm sorry that you are the one who
gets to deal with a noob.

I am building my own app with ng2-admin-lte as the foundation, so I need
to have a repo for that, that will never be merged up. At the same time, I
have some ideas and fixes that I would like to be able to contribute back
to your project. I'm not sure the best way to do that, and be able to pull
those and other changes to yours into my project as well.

Any suggestions? Or can you point me to documentation? I have tried
googling, but have not found anything useful yet.

**Comment by TwanoO67** [comment]
You can have several fork of à repo, so:
- Do à fork with thé général update you want to make,  then do à pull request for that
- Do à second fork, with your own code, that will never be merged back
