### ISSUE TITLE
Can't start

### ISSUE THREAD

**Issue by wenjiech** [TwanoO67/ng2-admin-lte#40]
Hi,when i use "npm start" it throw many errors like
![image](https://cloud.githubusercontent.com/assets/16333629/20912247/174b78be-bba9-11e6-8f2a-1463bface967.png), and i have this files. 
![image](https://cloud.githubusercontent.com/assets/16333629/20912281/43af0506-bba9-11e6-816c-812b54439d2a.png).
how can i fix it ,tks

**Comment by TwanoO67** [comment]
Hello, 

You don't have to worry for all those error. 
Usually those error are popped when you have an one first error that crash the typescript parsing. Can you send us the very first red line with an error ?

**Comment by wenjiech** [comment]
![image](https://cloud.githubusercontent.com/assets/16333629/20920854/9af535a0-bbdc-11e6-9c25-06dac3ebabdf.png)
it is the first line .
the whole error below.
** NG Live Development Server is running on http://localhost:4200. **
Hash: 31e4a83657b19a3b2d54
Time: 21687ms
chunk    {0} main.bundle.js, main.bundle.map (main) 49.2 kB {3} [initial] [rendered]
chunk    {1} styles.bundle.js, styles.bundle.map (styles) 423 kB {4} [initial] [rendered]
chunk    {2} scripts.bundle.js, scripts.bundle.map (scripts) 360 kB {4} [initial] [rendered]
chunk    {3} vendor.bundle.js, vendor.bundle.map (vendor) 5.38 MB [initial] [rendered]
chunk    {4} inline.bundle.js, inline.bundle.map (inline) 0 bytes [entry] [rendered]

ERROR in ./src/app/widgets/user-box/user-box.component.ts
Module not found: Error: Can't resolve 'user-box.component.html' in 'E:\angular2Start\ng2-admin-lte-master\src\app\widgets\user-box'
 @ ./src/app/widgets/user-box/user-box.component.ts 28:22-56
 @ ./src/app/widgets/user-box/index.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi main

ERROR in ./src/app/widgets/user-box/user-box.component.ts
Module not found: Error: Can't resolve 'user-box.component.css' in 'E:\angular2Start\ng2-admin-lte-master\src\app\widgets\user-box'
 @ ./src/app/widgets/user-box/user-box.component.ts 29:21-54
 @ ./src/app/widgets/user-box/index.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi main

ERROR in ./src/app/widgets/menu-aside/menu-aside.component.ts
Module not found: Error: Can't resolve 'menu-aside.component.html' in 'E:\angular2Start\ng2-admin-lte-master\src\app\widgets\menu-aside'
 @ ./src/app/widgets/menu-aside/menu-aside.component.ts 81:22-58
 @ ./src/app/widgets/menu-aside/index.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi main

ERROR in ./src/app/widgets/menu-aside/menu-aside.component.ts
Module not found: Error: Can't resolve 'menu-aside.component.css' in 'E:\angular2Start\ng2-admin-lte-master\src\app\widgets\menu-aside'
 @ ./src/app/widgets/menu-aside/menu-aside.component.ts 82:21-56
 @ ./src/app/widgets/menu-aside/index.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi main

ERROR in ./src/app/widgets/notification-box/notification-box.component.ts
Module not found: Error: Can't resolve 'notification-box.component.html' in 'E:\angular2Start\ng2-admin-lte-master\src\app\widgets\notification-box'
 @ ./src/app/widgets/notification-box/notification-box.component.ts 19:22-64
 @ ./src/app/widgets/notification-box/index.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi main

ERROR in ./src/app/widgets/notification-box/notification-box.component.ts
Module not found: Error: Can't resolve 'notification-box.component.css' in 'E:\angular2Start\ng2-admin-lte-master\src\app\widgets\notification-box'
 @ ./src/app/widgets/notification-box/notification-box.component.ts 20:21-62
 @ ./src/app/widgets/notification-box/index.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi main

ERROR in ./src/app/widgets/messages-box/messages-box.component.ts
Module not found: Error: Can't resolve 'messages-box.component.html' in 'E:\angular2Start\ng2-admin-lte-master\src\app\widgets\messages-box'
 @ ./src/app/widgets/messages-box/messages-box.component.ts 28:22-60
 @ ./src/app/widgets/messages-box/index.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi main

ERROR in ./src/app/widgets/messages-box/messages-box.component.ts
Module not found: Error: Can't resolve 'messages-box.component.css' in 'E:\angular2Start\ng2-admin-lte-master\src\app\widgets\messages-box'
 @ ./src/app/widgets/messages-box/messages-box.component.ts 29:21-58
 @ ./src/app/widgets/messages-box/index.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi main

ERROR in ./src/app/widgets/app-header/app-header.component.ts
Module not found: Error: Can't resolve 'app-header.component.html' in 'E:\angular2Start\ng2-admin-lte-master\src\app\widgets\app-header'
 @ ./src/app/widgets/app-header/app-header.component.ts 19:22-58
 @ ./src/app/widgets/app-header/index.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi main

ERROR in ./src/app/widgets/app-header/app-header.component.ts
Module not found: Error: Can't resolve 'app-header.component.css' in 'E:\angular2Start\ng2-admin-lte-master\src\app\widgets\app-header'
 @ ./src/app/widgets/app-header/app-header.component.ts 20:21-56
 @ ./src/app/widgets/app-header/index.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi main

ERROR in ./src/app/widgets/tasks-box/tasks-box.component.ts
Module not found: Error: Can't resolve 'tasks-box.component.html' in 'E:\angular2Start\ng2-admin-lte-master\src\app\widgets\tasks-box'
 @ ./src/app/widgets/tasks-box/tasks-box.component.ts 20:22-57
 @ ./src/app/widgets/tasks-box/index.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi main

ERROR in ./src/app/widgets/tasks-box/tasks-box.component.ts
Module not found: Error: Can't resolve 'tasks-box.component.css' in 'E:\angular2Start\ng2-admin-lte-master\src\app\widgets\tasks-box'
 @ ./src/app/widgets/tasks-box/tasks-box.component.ts 21:21-55
 @ ./src/app/widgets/tasks-box/index.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi main

**Comment by TwanoO67** [comment]
Is your code accessible somewhere?
Is it just a fresh install ?
did you add something?

**Comment by wenjiech** [comment]
fresh install, add noting

**Comment by wenjiech** [comment]
![image](https://cloud.githubusercontent.com/assets/16333629/20923051/91fa342e-bbe5-11e6-8d83-ac4611bb2102.png)
my runtime environment

**Comment by TwanoO67** [comment]
Try maybe updating your node environnement

I'm currently on 6.3 and npm 3.10

**Comment by kevintd** [comment]
i have same problem here:
ERROR in ./src/app/widgets/app-header/app-header.component.ts
Module not found: Error: Can't resolve 'app-header.component.html' in '/home/dev                                                                             /sample/ng2-admin-lte/src/app/widgets/app-header'
 @ ./src/app/widgets/app-header/app-header.component.ts 19:22-58
 @ ./src/app/widgets/app-header/index.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi main

ERROR in ./src/app/widgets/app-header/app-header.component.ts
Module not found: Error: Can't resolve 'app-header.component.css' in '/home/dev/                                                                             sample/ng2-admin-lte/src/app/widgets/app-header'
 @ ./src/app/widgets/app-header/app-header.component.ts 20:21-56
 @ ./src/app/widgets/app-header/index.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi main

ERROR in ./src/app/widgets/menu-aside/menu-aside.component.ts
Module not found: Error: Can't resolve 'menu-aside.component.html' in '/home/dev                                                                             /sample/ng2-admin-lte/src/app/widgets/menu-aside'
 @ ./src/app/widgets/menu-aside/menu-aside.component.ts 81:22-58
 @ ./src/app/widgets/menu-aside/index.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi main

ERROR in ./src/app/widgets/menu-aside/menu-aside.component.ts
Module not found: Error: Can't resolve 'menu-aside.component.css' in '/home/dev/                                                                             sample/ng2-admin-lte/src/app/widgets/menu-aside'
 @ ./src/app/widgets/menu-aside/menu-aside.component.ts 82:21-56
 @ ./src/app/widgets/menu-aside/index.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi main

ERROR in ./src/app/widgets/notification-box/notification-box.component.ts
Module not found: Error: Can't resolve 'notification-box.component.html' in '/ho                                                                             me/dev/sample/ng2-admin-lte/src/app/widgets/notification-box'
 @ ./src/app/widgets/notification-box/notification-box.component.ts 19:22-64
 @ ./src/app/widgets/notification-box/index.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi main

ERROR in ./src/app/widgets/notification-box/notification-box.component.ts
Module not found: Error: Can't resolve 'notification-box.component.css' in '/hom                                                                             e/dev/sample/ng2-admin-lte/src/app/widgets/notification-box'
 @ ./src/app/widgets/notification-box/notification-box.component.ts 20:21-62
 @ ./src/app/widgets/notification-box/index.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi main

ERROR in ./src/app/widgets/messages-box/messages-box.component.ts
Module not found: Error: Can't resolve 'messages-box.component.html' in '/home/d                                                                             ev/sample/ng2-admin-lte/src/app/widgets/messages-box'
 @ ./src/app/widgets/messages-box/messages-box.component.ts 28:22-60
 @ ./src/app/widgets/messages-box/index.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi main

ERROR in ./src/app/widgets/messages-box/messages-box.component.ts
Module not found: Error: Can't resolve 'messages-box.component.css' in '/home/de                                                                             v/sample/ng2-admin-lte/src/app/widgets/messages-box'
 @ ./src/app/widgets/messages-box/messages-box.component.ts 29:21-58
 @ ./src/app/widgets/messages-box/index.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi main

ERROR in ./src/app/widgets/tasks-box/tasks-box.component.ts
Module not found: Error: Can't resolve 'tasks-box.component.html' in '/home/dev/                                                                             sample/ng2-admin-lte/src/app/widgets/tasks-box'
 @ ./src/app/widgets/tasks-box/tasks-box.component.ts 20:22-57
 @ ./src/app/widgets/tasks-box/index.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi main

ERROR in ./src/app/widgets/tasks-box/tasks-box.component.ts
Module not found: Error: Can't resolve 'tasks-box.component.css' in '/home/dev/s                                                                             ample/ng2-admin-lte/src/app/widgets/tasks-box'
 @ ./src/app/widgets/tasks-box/tasks-box.component.ts 21:21-55
 @ ./src/app/widgets/tasks-box/index.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi main

ERROR in ./src/app/widgets/user-box/user-box.component.ts
Module not found: Error: Can't resolve 'user-box.component.html' in '/home/dev/s                                                                             ample/ng2-admin-lte/src/app/widgets/user-box'
 @ ./src/app/widgets/user-box/user-box.component.ts 28:22-56
 @ ./src/app/widgets/user-box/index.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi main

ERROR in ./src/app/widgets/user-box/user-box.component.ts
Module not found: Error: Can't resolve 'user-box.component.css' in '/home/dev/sa                                                                             mple/ng2-admin-lte/src/app/widgets/user-box'
 @ ./src/app/widgets/user-box/user-box.component.ts 29:21-54
 @ ./src/app/widgets/user-box/index.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi main

P/s:
my version: node v7.2.0 and npm 3.10.9

Thanks for your contributions

**Comment by RodEsV** [comment]
same problem here!

**Comment by TwanoO67** [comment]
It's seems to be related to à new angular version. 
This should be fixed by @RodEsV his last commits
