### ISSUE TITLE
error: npm run prod 

### ISSUE THREAD

**Issue by chenguose** [TwanoO67/ng2-admin-lte#47]
ERROR in ./src/environments/environment.ts
Module build failed: Error: ENOENT: no such file or directory, open 'F:\Angular2-admin\ng2-admin-lte\src\environments\environment.prod.ts'
    at Error (native)
 @ ./src/main.ts 4:0-57
 @ multi main

How can I fixed it?

**Comment by TwanoO67** [comment]
Créate the file environnent.prod.ts with the good configuration you need for this env
