### ISSUE TITLE
How to create login page

### ISSUE THREAD

**Issue by samir-kamble** [TwanoO67/ng2-admin-lte#62]
Hello,

Many thanks for awesome Angular 2 conversion of theme. I want to ask a small doubt that how do i create login page component. I am not using auth 0. I want to have login box without side menu.

**Comment by TwanoO67** [comment]
Hello, 

Here is the menu inclusion:
https://github.com/TwanoO67/ng2-admin-lte/blob/master/src/app/app.component.html

You can simply use an AuthService or a UserService to share an object between your components.
Then use this object state in the template with *ngIf to hide the component that you dont need
