### ISSUE TITLE
Router links not working when ported over to Apache cordova

### ISSUE THREAD

**Issue by samir-kamble** [TwanoO67/ng2-admin-lte#63]
Hi,

When I ported application over apache cordova it stopped navigation between pages. Can you please help?

**Comment by TwanoO67** [comment]
Hello, 

I dont know for cordova but I tried à porting to ionic2 and it usés à différent router. 
You can find the project here: https://github.com/TwanoO67/ionic-startee

**Comment by samir-kamble** [comment]
Hi,

Can you please guide me how to use it?

**Comment by samir-kamble** [comment]
waiting for your response.

**Comment by TwanoO67** [comment]
Sorry samir I am actually on holiday with no computer, I cant help you with that. Maybe try contacting someone from the ionic2 community
