### ISSUE TITLE
Not start

### ISSUE THREAD

**Issue by dantavo** [TwanoO67/ng2-admin-lte#65]
After installing the ng serve command fail for a problem with firebase, after installing firebase, I restart and give another problem with the load of listlazyrouting

**Comment by TwanoO67** [comment]
Hello,  
Can you give you ng --version informations ?

**Comment by dantavo** [comment]
ng -v
angular-cli: 1.0.0-beta.24
node: 6.9.4

**Comment by TwanoO67** [comment]
Hello

the problem with firebase is fixed.

For the lazyrouting, Try updating to :
angular-cli: 1.0.0-beta.26
node: 7.2.0

then:
git pull
rm -rf node_modules
npm cache clear
npm start

**Comment by TwanoO67** [comment]
is it ok for you @dantavo ?

**Comment by dantavo** [comment]
Hi the problem is fixed but I have another problem at startup:
EXCEPTION: Error in ./AppComponent class AppComponent - inline template:0:0 caused by: Auth0 is not a constructor
now I have beta.26 for angular cli and node 7.4.0

**Comment by TwanoO67** [comment]
Ok, for that we will discuss on issue #66
