### ISSUE TITLE
I tried git push origin master

### ISSUE THREAD

**Issue by ezekylellorca** [TwanoO67/ng2-admin-lte#69]
remote: Permission to TwanoO67/ng2-admin-lte.git denied to ezekylellorca.
fatal: unable to access 'https://github.com/TwanoO67/ng2-admin-lte.git/': The requested URL returned error: 403

please help me with this

Thanks,

**Comment by michaelarnauts** [comment]
You can only push to repos you have access to.

**Comment by ezekylellorca** [comment]
I'm trying to deploy it just like this but it says i don't have a permission

https://ezekylellorca.github.io/enigmatic-falls-84115

**Comment by TwanoO67** [comment]
If you want to use github pages to deploy, you need to do that on your own fork

**Comment by TwanoO67** [comment]
it seems that @ezekylellorca fixed his page ;)

**Comment by ezekylellorca** [comment]
yes, it's i just change the setting of Github Pages Source from none to
master is that ok?
