### ISSUE TITLE
How do I preview all pages?

### ISSUE THREAD

**Issue by amitjindal** [TwanoO67/ng2-admin-lte#73]
Hi, Sorry, this seems like a trivial question but I have tried to run this with `npm start` and also with `./bin/start.sh`.
I get to login page, enter a fake value for username/password and it keeps redirecting me to login.
I didn't find any username/password I should specify. How do I view this project running?

**Comment by TwanoO67** [comment]
Hello,

You should just hit the login button, no username is required.

Maybe what you describe seems like à bug with using the 'enter' key for submiting the form

**Comment by TwanoO67** [comment]
It should be easier now ;)

**Comment by TwanoO67** [comment]
Is it ok for you ? @amitjindal

**Comment by amitjindal** [comment]
I tried. It was showing some weird behavior. Randomly when I was clicking inner pages, it was redirecting to Login. I did clear cache and also used Incognito mode.
So I left this template aside.
The original bug seems fixed so we can close this.

**Comment by TwanoO67** [comment]
The redirection to the login page is not à random behavior.
Some part of the template still have "href" links and not routerLinks, that's why it's redirecting to the login pages, because it reload the SPA
