### ISSUE TITLE
Unable to build project. Can not read property length of undefined

### ISSUE THREAD

**Issue by AhsanAyaz** [TwanoO67/ng2-admin-lte#74]
<img width="1280" alt="screen shot 2017-03-06 at 12 04 00 am" src="https://cloud.githubusercontent.com/assets/9844254/23590384/935c5098-0200-11e7-8d53-08eefacd5293.png">

Having this issue when trying to build the project.

node version v7.7.1

**Comment by TwanoO67** [comment]
It's seems that your angular-cli installation is too old. Try using the local one. Or building using the docker script

**Comment by AhsanAyaz** [comment]
For some reason, the dev serve and build were working fine and --prod was breaking. 
Built using docker fixed the issue. 
Thanks.
