### ISSUE TITLE
getting error while starting npm

### ISSUE THREAD

**Issue by nileshyadav326** [TwanoO67/ng2-admin-lte#82]
npm WARN deprecated ng2-bootstrap@1.6.3: DEPRECATED: package was renamed to ngx-bootstrap
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

**Comment by TwanoO67** [comment]
Hello,

this bootstraping is on angular2 version, so it will stay on those packages at the moment.
but a new one is under developement for the angular4 portage, here:
https://github.com/TwanoO67/ngx-admin-lte

**Comment by nileshyadav326** [comment]
Thanks, TwanoO67 thanks for all your efforts.
